// 0000 - Consultas
// 1000 - Agregar
// 2000 - Editar
// 3000 - Eliminar
export class CodigoAcceso {
  public static CONSULTAR_AREA = 'APAREA0000';
  public static AGREGAR_AREA = 'APAREA1000';
  public static EDITAR_AREA = 'APAREA2000';
  public static ELIMINAR_AREA = 'APAREA3000';

  public static CONSULTAR_CUENTA_CONTABLE = 'APCUCO0000';
  public static AGREGAR_CUENTA_CONTABLE = 'APCUCO1000';
  public static EDITAR_CUENTA_CONTABLE = 'APCUCO2000';
  public static ELIMINAR_CUENTA_CONTABLE = 'APCUCO3000';

  public static CONSULTAR_TURNO = 'APTURN0000';
  public static AGREGAR_TURNO = 'APTURN1000';
  public static EDITAR_TURNO = 'APTURN2000';
  public static ELIMINAR_TURNO = 'APTURN3000';

  public static CONSULTAR_FORMA_PAGO = 'APFMPG0000';
  public static AGREGAR_FORMA_PAGO = 'APFMPG1000';
  public static EDITAR_FORMA_PAGO = 'APFMPG2000';
  public static ELIMINAR_FORMA_PAGO = 'APFMPG3000';

  public static CONSULTAR_BANCO = 'APBANC0000';
  public static AGREGAR_BANCO = 'APBANC1000';
  public static EDITAR_BANCO = 'APBANC2000';
  public static ELIMINAR_BANCO = 'APBANC3000';

  public static CONSULTAR_CONCEPTO = 'APCNPT0000';
  public static AGREGAR_CONCEPTO = 'APCNPT1000';
  public static EDITAR_CONCEPTO = 'APCNPT2000';
  public static ELIMINAR_CONCEPTO = 'APCNPT3000';

  public static CONSULTAR_IMPUESTO = 'APIMPT0000';
  public static AGREGAR_IMPUESTO = 'APIMPT1000';
  public static EDITAR_IMPUESTO = 'APIMPT2000';
  public static ELIMINAR_IMPUESTO = 'APIMPT3000';

  public static CONSULTAR_PAIS = 'APPAIS0000';
  public static AGREGAR_PAIS = 'APPAIS1000';
  public static EDITAR_PAIS = 'APPAIS2000';
  public static ELIMINAR_PAIS = 'APPAIS3000';

  //Genero
  public static CONSULTAR_GENERO = 'APGENERO0000';
  public static AGREGAR_GENERO = 'APGENERO1000';
  public static EDITAR_GENERO = 'APGENERO2000';
  public static ELIMINAR_GENERO = 'APGENERO3000';

  public static CONSULTAR_CAJA = 'APCAJA0000';
  public static AGREGAR_CAJA = 'APCAJA1000';
  public static EDITAR_CAJA = 'APCAJA2000';
  public static ELIMINAR_CAJA = 'APCAJA3000';

  public static CONSULTAR_ESTADO = 'APESDO0000';
  public static AGREGAR_ESTADO = 'APESDO1000';
  public static EDITAR_ESTADO = 'APESDO2000';
  public static ELIMINAR_ESTADO = 'APESDO3000';

  public static CONSULTAR_COMPANIA = 'APCMPA0000';
  public static AGREGAR_COMPANIA = 'APCMPA1000';
  public static EDITAR_COMPANIA = 'APCMPA2000';
  public static ELIMINAR_COMPANIA = 'APCMPA3000';
  public static EDITAR_COMPANIA_HORA = 'APCMPA4000';

  public static CONSULTAR_ACCESO = 'APACCE0000';
  public static REPORTE_ARBOL_ACCESO = 'APACCE0001';
  public static AGREGAR_ACCESO = 'APACCE1000';
  public static EDITAR_ACCESO = 'APACCE2000';
  public static ELIMINAR_ACCESO = 'APACCE3000';

  public static CONSULTAR_JERARQUIA_ACCESO = 'APJEAC0000';
  public static AGREGAR_JERARQUIA_ACCESO = 'APJEAC1000';
  public static EDITAR_JERARQUIA_ACCESO = 'APJEAC2000';
  public static ELIMINAR_JERARQUIA_ACCESO = 'APJEAC3000';

  public static CONSULTAR_PERFIL = 'APPERF0000';
  public static AGREGAR_PERFIL = 'APPERF1000';
  public static EDITAR_PERFIL = 'APPERF2000';
  public static ELIMINAR_PERFIL = 'APPERF3000';

  public static CONSULTAR_USUARIO = 'APUSUA0000';
  public static AGREGAR_USUARIO = 'APUSUA1000';
  public static EDITAR_USUARIO = 'APUSUA2000';
  public static ELIMINAR_USUARIO = 'APUSUA3000';
  public static EDITAR_CONTRASENA_USUARIO = 'APUSUA4000';

  public static CONSULTAR_ARTICULO = 'APARTC0000';
  public static AGREGAR_ARTICULO = 'APARTC1000';
  public static EDITAR_ARTICULO = 'APARTC2000';
  public static ELIMINAR_ARTICULO = 'APARTC3000';

  public static CONSULTAR_DEPARTAMENTO = 'APDPTO0000';
  public static AGREGAR_DEPARTAMENTO = 'APDPTO1000';
  public static EDITAR_DEPARTAMENTO = 'APDPTO2000';
  public static ELIMINAR_DEPARTAMENTO = 'APDPTO3000';

  public static CONSULTAR_MOTIVO_VISITA = 'APMTVS0000';
  public static AGREGAR_MOTIVO_VISITA = 'APMTVS1000';
  public static EDITAR_MOTIVO_VISITA = 'APMTVS2000';
  public static ELIMINAR_MOTIVO_VISITA = 'APMTVS3000';

  public static CONSULTAR_VIA_ADMINISTRACION = 'APVIAD0000';
  public static AGREGAR_VIA_ADMINISTRACION = 'APVIAD1000';
  public static EDITAR_VIA_ADMINISTRACION = 'APVIAD2000';
  public static ELIMINAR_VIA_ADMINISTRACION = 'APVIAD3000';

  public static CONSULTAR_DOMINIO = 'APDOMN0000';
  public static AGREGAR_DOMINIO = 'APDOMN1000';
  public static EDITAR_DOMINIO = 'APDOMN2000';
  public static ELIMINAR_DOMINIO = 'APDOMN3000';

  public static CONSULTAR_EXPEDIENTE = 'APEXPE0000';
  public static CONSULTAR_POR_FILTRO_EXPEDIENTE = 'APEXPE0001';
  public static AGREGAR_EXPEDIENTE = 'APEXPE1000';
  public static EDITAR_EXPEDIENTE = 'APEXPE2000';
  public static ELIMINAR_EXPEDIENTE = 'APEXPE3000';

  public static CONSULTAR_EXPEDIENTE_PACIENTE_INFORMACION = 'APEXPI0000';
  public static AGREGAR_EXPEDIENTE_PACIENTE_INFORMACION = 'APEXPI1000';
  public static EDITAR_EXPEDIENTE_PACIENTE_INFORMACION = 'APEXPI2000';
  public static ELIMINAR_EXPEDIENTE_PACIENTE_INFORMACION = 'APEXPI3000';

  public static CONSULTAR_EXPEDIENTE_DATO_SOCIAL = 'APEXDS0000';
  public static AGREGAR_EXPEDIENTE_DATO_SOCIAL = 'APEXDS1000';
  public static EDITAR_EXPEDIENTE_DATO_SOCIAL = 'APEXDS2000';
  public static ELIMINAR_EXPEDIENTE_DATO_SOCIAL = 'APEXDS3000';

  public static CONSULTAR_TITULO_ACADEMICO = 'APTIAC0000';
  public static AGREGAR_TITULO_ACADEMICO = 'APTIAC1000';
  public static EDITAR_TITULO_ACADEMICO = 'APTIAC2000';
  public static ELIMINAR_TITULO_ACADEMICO = 'APTIAC3000';

  public static CONSULTAR_SERVICIO = 'APSERV0000';
  public static AGREGAR_SERVICIO = 'APSERV1000';
  public static EDITAR_SERVICIO = 'APSERV2000';
  public static ELIMINAR_SERVICIO = 'APSERV3000';

  public static CONSULTAR_ARTICULO_PRESENTACION = 'APARPR0000';
  public static AGREGAR_ARTICULO_PRESENTACION = 'APARPR1000';
  public static EDITAR_ARTICULO_PRESENTACION = 'APARPR2000';
  public static ELIMINAR_ARTICULO_PRESENTACION = 'APARPR3000';

  public static CONSULTAR_FABRICANTE = 'APFBRT0000';
  public static AGREGAR_FABRICANTE = 'APFBRT1000';
  public static EDITAR_FABRICANTE = 'APFBRT2000';
  public static ELIMINAR_FABRICANTE = 'APFBRT3000';

  public static CONSULTAR_TIPO_DESCUENTO = 'APTPDC0000';
  public static AGREGAR_TIPO_DESCUENTO = 'APTPDC1000';
  public static EDITAR_TIPO_DESCUENTO = 'APTPDC2000';
  public static ELIMINAR_TIPO_DESCUENTO = 'APTPDC3000';

  public static CONSULTAR_ARTICULO_CLASE = 'APATCS0000';
  public static AGREGAR_ARTICULO_CLASE = 'APATCS1000';
  public static EDITAR_ARTICULO_CLASE = 'APATCS2000';
  public static ELIMINAR_ARTICULO_CLASE = 'APATCS3000';

  public static CONSULTAR_TIPO_COMISION = 'APTPCM0000';
  public static AGREGAR_TIPO_COMISION = 'APTPCM1000';
  public static EDITAR_TIPO_COMISION = 'APTPCM2000';
  public static ELIMINAR_TIPO_COMISION = 'APTPCM3000';

  public static CONSULTAR_PRESENTACION = 'APPRES0000';
  public static AGREGAR_PRESENTACION = 'APPRES1000';
  public static EDITAR_PRESENTACION = 'APPRES2000';
  public static ELIMINAR_PRESENTACION = 'APPRES3000';

  public static CONSULTAR_TIPO_PROVEEDOR = 'APTPPV0000';
  public static AGREGAR_TIPO_PROVEEDOR = 'APTPPV1000';
  public static EDITAR_TIPO_PROVEEDOR = 'APTPPV2000';
  public static ELIMINAR_TIPO_PROVEEDOR = 'APTPPV3000';

  public static CONSULTAR_UNIDAD_MEDIDA = 'APUNMD0000';
  public static AGREGAR_UNIDAD_MEDIDA = 'APUNMD1000';
  public static EDITAR_UNIDAD_MEDIDA = 'APUNMD2000';
  public static ELIMINAR_UNIDAD_MEDIDA = 'APUNMD3000';

  public static CONSULTAR_PARENTESCO = 'APPRTC0000';
  public static AGREGAR_PARENTESCO = 'APPRTC1000';
  public static EDITAR_PARENTESCO = 'APPRTC2000';
  public static ELIMINAR_PARENTESCO = 'APPRTC3000';

  public static CONSULTAR_HOSPITAL = 'APHOSP0000';
  public static AGREGAR_HOSPITAL = 'APHOSP1000';
  public static EDITAR_HOSPITAL = 'APHOSP2000';
  public static ELIMINAR_HOSPITAL = 'APHOSP3000';

  public static CONSULTAR_ESTADO_CIVIL = 'APEDCV0000';
  public static AGREGAR_ESTADO_CIVIL = 'APEDCV1000';
  public static EDITAR_ESTADO_CIVIL = 'APEDCV2000';
  public static ELIMINAR_ESTADO_CIVIL = 'APEDCV3000';

  public static CONSULTAR_GRUPO_SANGUINEO = 'APGPSG0000';
  public static AGREGAR_GRUPO_SANGUINEO = 'APGPSG1000';
  public static EDITAR_GRUPO_SANGUINEO = 'APGPSG2000';
  public static ELIMINAR_GRUPO_SANGUINEO = 'APGPSG3000';

  public static CONSULTAR_MUNICIPIO = 'APMUCP0000';
  public static AGREGAR_MUNICIPIO = 'APMUCP1000';
  public static EDITAR_MUNICIPIO = 'APMUCP2000';
  public static ELIMINAR_MUNICIPIO = 'APMUCP3000';

  public static CONSULTAR_FACTOR_RH = 'APFCRH0000';
  public static AGREGAR_FACTOR_RH = 'APFCRH1000';
  public static EDITAR_FACTOR_RH = 'APFCRH2000';
  public static ELIMINAR_FACTOR_RH = 'APFCRH3000';

  public static CONSULTAR_PUNTODEVENTA = 'APPTVT0000';
  public static COMPRA_PUNTODEVENTA = 'APPTVT1000';
  public static VER_REPORTE_TICKET_VENTA = 'APPTVT2000';

  public static CONSULTAR_RECIBOS = 'APGERB0000';
  public static VER_REPORTE_RECIBO_PAGO = 'APGERB1000';

  public static CONSULTAR_TIPO_IDENTIFICACION = 'APTPID0000';
  public static AGREGAR_TIPO_IDENTIFICACION = 'APTPID1000';
  public static EDITAR_TIPO_IDENTIFICACION = 'APTPID2000';
  public static ELIMINAR_TIPO_IDENTIFICACION = 'APTPID3000';

  public static CONSULTAR_TIPO_PRESENTACION = 'APTPPS0000';
  public static AGREGAR_TIPO_PRESENTACION = 'APTPPS1000';
  public static EDITAR_TIPO_PRESENTACION = 'APTPPS2000';
  public static ELIMINAR_TIPO_PRESENTACION = 'APTPPS3000';

  public static CONSULTAR_PACIENTE = 'APPCTE0000';
  public static AGREGAR_PACIENTE = 'APPCTE1000';
  public static EDITAR_PACIENTE = 'APPCTE2000';
  public static ELIMINAR_PACIENTE = 'APPCTE3000';

  public static CONSULTAR_LOCALIDAD = 'APLCLD0000';
  public static AGREGAR_LOCALIDAD = 'APLCLD1000';
  public static EDITAR_LOCALIDAD = 'APLCLD2000';
  public static ELIMINAR_LOCALIDAD = 'APLCLD3000';

  public static CONSULTAR_CATEGORIA = 'APCTGR0000';
  public static AGREGAR_CATEGORIA = 'APCTGR1000';
  public static EDITAR_CATEGORIA = 'APCTGR2000';
  public static ELIMINAR_CATEGORIA = 'APCTGR3000';

  public static CONSULTAR_TIPO_IMPUESTO = 'APTPIM0000';
  public static AGREGAR_TIPO_IMPUESTO = 'APTPIM1000';
  public static EDITAR_TIPO_IMPUESTO = 'APTPIM2000';
  public static ELIMINAR_TIPO_IMPUESTO = 'APTPIM3000';

  public static CONSULTAR_TIPO_CONCEPTO = 'APTPCO0000';
  public static AGREGAR_TIPO_CONCEPTO = 'APTPCO1000';
  public static EDITAR_TIPO_CONCEPTO = 'APTPCO2000';
  public static ELIMINAR_TIPO_CONCEPTO = 'APTPCO3000';

  public static CONSULTAR_GIRO_COMERCIAL = 'APGICO0000';
  public static AGREGAR_GIRO_COMERCIAL = 'APGICO1000';
  public static EDITAR_GIRO_COMERCIAL = 'APGICO2000';
  public static ELIMINAR_GIRO_COMERCIAL = 'APGICO3000';

  public static CONSULTAR_TIPO_FLUJO = 'APTPFL0000';
  public static AGREGAR_TIPO_FLUJO = 'APTPFL1000';
  public static EDITAR_TIPO_FLUJO = 'APTPFL2000';
  public static ELIMINAR_TIPO_FLUJO = 'APTPFL3000';

  public static CONSULTAR_CONFIGURACION_VIGENCIA = 'APCOVI0000';
  public static AGREGAR_CONFIGURACION_VIGENCIA = 'APCOVI1000';
  public static EDITAR_CONFIGURACION_VIGENCIA = 'APCOVI2000';
  public static ELIMINAR_CONFIGURACION_VIGENCIA = 'APCOVI3000';

  public static CONSULTAR_TIPO_VIGENCIA = 'APTIVI0000';
  public static AGREGAR_TIPO_VIGENCIA = 'APTIVI1000';
  public static EDITAR_TIPO_VIGENCIA = 'APTIVI2000';
  public static ELIMINAR_TIPO_VIGENCIA = 'APTIVI3000';


  // Diario Medico y Triage

  public static CONSULTAR_DIARIO_MEDICO = 'APDMTR0000';
  public static AGREGAR_DIARIO_MEDICO = 'APDMTR1000';
  public static EDITAR_DIARIO_MEDICO = 'APDMTR2000';
  public static ELIMINAR_DIARIO_MEDICO = 'APDMTR3000';

  public static CONSULTAR_DIARIO_MEDICO_CONSULTA_MEDICA_GENERAL = 'APCMDG0000';
  public static CONSULTAR_DIARIO_MEDICO_NOTA_EVOLUCION = 'APNTEV0000';
  public static CONSULTAR_DIARIO_MEDICO_LINEA_VIDA = 'APLNVD0000';
  public static CONSULTAR_DIARIO_MEDICO_NOTA_REFERENCIA = 'APNTRF0000';
  public static CONSULTAR_DIARIO_MEDICO_SOMATOMETRIA = 'APDSOM0000';
  public static CONSULTAR_DIARIO_MEDICO_ORDEN_LABORATORIO = 'APDORL0000';
  public static CONSULTAR_DIARIO_MEDICO_ORDEN_IMAGENOLOGIA = 'APDORI0000';

  public static CONSULTAR_DIARIO_MEDICO_RECETAS = 'APRCTA0000';
  public static AGREGAR_DIARIO_MEDICO_RECETA = 'APRCTA1000';
  public static EDITAR_DIARIO_MEDICO_RECETA = 'APRCTA2000';
  public static ELIMINAR_DIARIO_MEDICO_RECETA = 'APRCTA3000';

  // Punto de Venta

  public static CONSULTAR_PUNTO_VENTA = 'APCPTV0000';
  public static AGREGAR_PUNTO_VENTA = 'APCPTV1000';
  public static EDITAR_PUNTO_VENTA = 'APCPTV2000';
  public static ELIMINAR_PUNTO_VENTA = 'APCPTV3000';

  public static CONSULTAR_TIPO_PUNTO_VENTA = 'APTPVT0000';
  public static AGREGAR_TIPO_PUNTO_VENTA = 'APTPVT1000';
  public static EDITAR_TIPO_PUNTO_VENTA = 'APTPVT2000';
  public static ELIMINAR_TIPO_PUNTO_VENTA = 'APTPVT3000';

  public static CONSULTAR_CITA = 'APCITA0000';
  public static CONSULTAR_POR_FILTRO_CITA = 'APCITA0001';
  public static AGREGAR_CITA = 'APCITA1000';
  public static EDITAR_CITA = 'APCITA2000';
  public static ELIMINAR_CITA = 'APCITA3000';

  public static CONSULTAR_LABORATORIO = 'APLABO0000';
  public static AGREGAR_LABORATORIO = 'APLABO1000';
  public static EDITAR_LABORATORIO = 'APLABO2000';
  public static ELIMINAR_LABORATORIO = 'APLABO3000';

  public static CONSULTAR_ESTUDIO_LABORATORIO = 'APESLA0000';
  public static AGREGAR_ESTUDIO_LABORATORIO = 'APESLA1000';
  public static EDITAR_ESTUDIO_LABORATORIO = 'APESLA2000';
  public static ELIMINAR_ESTUDIO_LABORATORIO = 'APESLA3000';

  public static CONSULTAR_MUESTRA_LABORATORIO = 'APMULA0000';
  public static AGREGAR_MUESTRA_LABORATORIO = 'APMULA1000';
  public static EDITAR_MUESTRA_LABORATORIO = 'APMULA2000';
  public static ELIMINAR_MUESTRA_LABORATORIO = 'APMULA3000';

  public static CONSULTAR_NOTA_VENTA = 'APNOVE0000';
  public static AGREGAR_NOTA_VENTA = 'APNOVE1000';
  public static EDITAR_NOTA_VENTA = 'APNOVE2000';
  public static ELIMINAR_NOTA_VENTA = 'APNOVE3000';

  public static CONSULTAR_PROVEEDOR = 'APPRVD0000';
  public static AGREGAR_PROVEEDOR = 'APPRVD1000';
  public static EDITAR_PROVEEDOR = 'APPRVD2000';
  public static ELIMINAR_PROVEEDOR = 'APPRVD3000';

  public static CONSULTAR_DOMICILIO = 'APDMCL0000';
  public static AGREGAR_DOMICILIO = 'APDMCL1000';
  public static EDITAR_DOMICILIO = 'APDMCL2000';
  public static ELIMINAR_DOMICILIO = 'APDMCL3000';

  public static CONSULTAR_UBICACION = 'APUBCN0000';
  public static AGREGAR_UBICACION = 'APUBCN0000';
  public static EDITAR_UBICACION = 'APUBCN0000';
  public static ELIMINAR_UBICACION = 'APUBCN0000';

  public static CONSULTAR_IMAGENOLOGIA = 'APIMGO0000';
  public static AGREGAR_IMAGENOLOGIA = 'APIMGO1000';
  public static EDITAR_IMAGENOLOGIA = 'APIMGO2000';
  public static ELIMINAR_IMAGENOLOGIA = 'APIMGO3000';

  public static CONSULTAR_CODIGO_POSTAL = 'APCDPS0000';
  public static AGREGAR_CODIGO_POSTAL = 'APCDPS1000';
  public static EDITAR_CODIGO_POSTAL = 'APCDPS2000';
  public static ELIMINAR_CODIGO_POSTAL = 'APCDPS3000';

  public static CONSULTAR_ROL = 'APROLS0000';
  public static AGREGAR_ROL = 'APROLS1000';
  public static EDITAR_ROL = 'APROLS2000';
  public static ELIMINAR_ROL = 'APROLS3000';

  public static CONSULTAR_DATO_SOCIAL = 'APDTSC0000';
  public static AGREGAR_DATO_SOCIAL = 'APDTSC1000';
  public static EDITAR_DATO_SOCIAL = 'APDTSC2000';
  public static ELIMINAR_DATO_SOCIAL = 'APDTSC3000';

  public static CONSULTAR_DATO_ADICIONAL = 'APDTAD0000';
  public static AGREGAR_DATO_ADICIONAL = 'APDTAD1000';
  public static EDITAR_DATO_ADICIONAL = 'APDTAD2000';
  public static ELIMINAR_DATO_ADICIONAL = 'APDTAD3000';

  public static CONSULTAR_ANTECEDENTE_CLINICO = 'APANCC0000';
  public static AGREGAR_ANTECEDENTE_CLINICO = 'APANCC1000';
  public static EDITAR_ANTECEDENTE_CLINICO = 'APANCC2000';
  public static ELIMINAR_ANTECEDENTE_CLINICO = 'APANCC3000';

  public static CONSULTAR_UBICACION_VENTA = 'APUBVA0000';
  public static AGREGAR_UBICACION_VENTA = 'APUBVA1000';
  public static EDITAR_UBICACION_VENTA = 'APUBVA2000';
  public static ELIMINAR_UBICACION_VENTA = 'APUBVA3000';

  public static CONSULTAR_TIPO_MUESTRA = 'APMUES0000';
  public static AGREGAR_TIPO_MUESTRA = 'APMUES1000';
  public static EDITAR_TIPO_MUESTRA = 'APMUES2000';
  public static ELIMINAR_TIPO_MUESTRA = 'APMUES3000';

  public static CONSULTAR_ENTRADA_PERSONAL = 'APEPER0000';
  public static REPORTE_USUARIO_COMISION = 'APEPER0001';
  public static AGREGAR_ENTRADA_PERSONAL = 'APEPER1000';
  public static EDITAR_ENTRADA_PERSONAL = 'APEPER2000';
  public static ELIMINAR_ENTRADA_PERSONAL = 'APEPER3000';

  public static CONSULTAR_CIE = 'APCCIE0000';
  public static AGREGAR_CIE = 'APCCIE1000';
  public static EDITAR_CIE = 'APCCIE2000';
  public static ELIMINAR_CIE = 'APCCIE3000';

  public static CONSULTAR_ENFERMEDADES = 'APENFM0000';
  public static AGREGAR_ENFERMEDADES = 'APENFM1000';
  public static EDITAR_ENFERMEDADES = 'APENFM2000';
  public static ELIMINAR_ENFERMEDADES = 'APENFM3000';

  public static CONSULTAR_MOVIMIENTO_MATERIAL = 'APMOMA0000';
  public static AGREGAR_MOVIMIENTO_MATERIAL = 'APMOMA1000';
  public static CANCELAR_MOVIMIENTO_MATERIAL = 'APMOMA3000';

  public static CONSULTAR_TIPO_MOVIMIENTO_MATERIAL = 'APTPMV0000';
  public static AGREGAR_TIPO_MOVIMIENTO_MATERIAL = 'APTPMV1000';
  public static EDITAR_TIPO_MOVIMIENTO_MATERIAL = 'APTPMV2000';
  public static ELIMINAR_TIPO_MOVIMIENTO_MATERIAL = 'APTPMV3000';

  public static CONSULTAR_FLUJO = 'APFLUJ0000';
  public static AGREGAR_FLUJO = 'APFLUJ1000';
  public static EDITAR_FLUJO = 'APFLUJ2000';
  public static ELIMINAR_FLUJO = 'APFLUJ3000';

  public static CONSULTAR_TIPO_POLIZA = 'APTPPZ0000';
  public static AGREGAR_TIPO_POLIZA = 'APTPPZ1000';
  public static EDITAR_TIPO_POLIZA = 'APTPPZ2000';
  public static ELIMINAR_TIPO_POLIZA = 'APTPPZ3000';

  public static CONSULTAR_MONEDA = 'APMOCP0000';
  public static AGREGAR_MONEDA = 'APMOCP1000 ';
  public static EDITAR_MONEDA = 'APMOCP2000';
  public static ELIMINAR_MONEDA = 'APMOCP3000';

  public static CONSULTAR_AUXILIAR = 'APAUX0000';
  public static AGREGAR_AUXILIAR = 'APAUX1000';
  public static EDITAR_AUXILIAR = 'APAUX2000';
  public static ELIMINAR_AUXILIAR = 'APAUX3000';

  public static CONSULTAR_AGRUPADOR_CUENTA_CONTABLE = 'APCTAC0000';
  public static AGREGAR_AGRUPADOR_CUENTA_CONTABLE = 'APCTAC1000';
  public static EDITAR_AGRUPADOR_CUENTA_CONTABLE = 'APCTAC2000';
  public static ELIMINAR_AGRUPADOR_CUENTA_CONTABLE = 'APCTAC3000';

  public static CONSULTAR_TIPO_CAMBIO = 'APTCCO0000';
  public static AGREGAR_TIPO_CAMBIO = 'APTCCO1000';
  public static EDITAR_TIPO_CAMBIO = 'APTCCO2000';
  public static ELIMINAR_TIPO_CAMBIO = 'APTCCO3000';

  public static CONSULTAR_CARGA_MASIVA_POLIZA = 'APEPCM0000';

  public static CONSULTAR_POLIZA = 'APPLZA0000';
  public static AGREGAR_POLIZA = 'APPLZA1000';
  public static EDITAR_POLIZA = 'APPLZA2000';
  public static ELIMINAR_POLIZA = 'APPLZA3000';

  public static CONSULTAR_POLIZA_DETALLE = 'APPLDT0000';
  public static AGREGAR_POLIZA_DETALLE = 'APPLDT1000';
  public static EDITAR_POLIZA_DETALLE = 'APPLZDT000';
  public static ELIMINAR_POLIZA_DETALLE = 'APPLDT3000';

  public static CONSULTAR_EXPEDIENTE_ADMINISTRATIVO = 'APEXAD0000';
  public static AGREGAR_EXPEDIENTE_ADMINISTRATIVO = 'APEXAD1000';
  public static EDITAR_EXPEDIENTE_ADMINISTRATIVO = 'APEXAD2000';
  public static ELIMINAR_EXPEDIENTE_ADMINISTRATIVO = 'APEXAD3000';

  public static CONSULTAR_VEHICULO = 'APVEHI0000';
  public static AGREGAR_VEHICULO = 'APVEHI1000';
  public static EDITAR_VEHICULO = 'APVEHI2000';
  public static ELIMINAR_VEHICULO = 'APVEHI3000';

  public static CONSULTAR_JERARQUIA_CUENTAS = 'APJECU0000';
  public static AGREGAR_JERARQUIA_CUENTAS = 'APJECU1000';
  public static EDITAR_JERARQUIA_CUENTAS = 'APJECU2000';
  public static ELIMINAR_JERARQUIA_CUENTAS = 'APJECU3000';

  public static CONSULTAR_JERARQUIA_AUXILIAR = 'APJEAU0000';
  public static AGREGAR_JERARQUIA_AUXILIAR = 'APJEAU1000';
  public static EDITAR_JERARQUIA_AUXILIAR = 'APJEAU2000';
  public static ELIMINAR_JERARQUIA_AUXILIAR = 'APJEAU3000';

  public static CONSULTAR_FACTURAS = 'APFACT0000';
  public static AGREGAR_FACTURA = 'APGNFC0000';

  public static CONSULTAR_CONFIGURACION_CONTABILIDAD = 'APCOCO0000';

  public static CONSULTAR_CONFIGURACION_EGRESOS = 'APEGCO0000';

  public static CONSULTAR_CIERRE_CONTABLE = 'APCIER0000';
  public static EDITAR_MANTENIMIENTO = 'APMANT2000';
  public static ElIMINAR_MANTENIMIENTO = 'APMANT3000';

  public static CONSULTAR_CARGA_MASIVA_MOVIMIENTOS = 'APCMMO0000';

  public static CONSULTAR_ESTATUS_PEDIDO = 'APCOEP0000';
  public static AGREGAR_ESTATUS_PEDIDO = 'APCOEP1000 ';
  public static EDITAR_ESTATUS_PEDIDO = 'APCOEP2000';
  public static ELIMINAR_ESTATUS_PEDIDO = 'APCOEP3000';

  public static CONSULTAR_COLONIA = 'APCLNA0000';
  public static AGREGAR_COLONIA = 'APCLNA1000';
  public static EDITAR_COLONIA = 'APCLNA2000';
  public static ELIMINAR_COLONIA = 'APCLNA3000';

  public static CONSULTAR_PRODUCTO_SERVICIO_CARTA_PORTE = 'APFACP0000';
  public static AGREGAR_PRODUCTO_SERVICIO_CARTA_PORTE = 'APFACP1000';
  public static EDITAR_PRODUCTO_SERVICIO_CARTA_PORTE = 'APFACP2000';
  public static ELIMINAR_PRODUCTO_SERVICIO_CARTA_PORTE = 'APFACP3000';

  public static CONSULTAR_TIPO_COMPANIA = 'APTICO0000';
  public static AGREGAR_TIPO_COMPANIA = 'APTICO1000';
  public static EDITAR_TIPO_COMPANIA = 'APTICO2000';
  public static ELIMINAR_TIPO_COMPANIA = 'APTICO3000';

  public static CONSULTAR_AYUDA_SECCION = 'APAYSE0000';
  public static AGREGAR_AYUDA_SECCION = 'APAYSE1000';
  public static EDITAR_AYUDA_SECCION = 'APAYSE2000';
  public static ELIMINAR_AYUDA_SECCION = 'APAYSE3000';

  public static CONSULTAR_TIPO_AUXILIAR = 'APTAUX0000';
  public static AGREGAR_TIPO_AUXILIAR = 'APTAUX1000';
  public static EDITAR_TIPO_AUXILIAR = 'APTAUX2000';
  public static ELIMINAR_TIPO_AUXILIAR = 'APTAUX3000';

  public static CONSULTAR_TIPO_CUENTA_CONTABLE = 'APTPCC0000';
  public static AGREGAR_TIPO_CUENTA_CONTABLE = 'APTPCC1000';
  public static EDITAR_TIPO_CUENTA_CONTABLE = 'APTPCC2000';
  public static ELIMINAR_TIPO_CUENTA_CONTABLE = 'APTPCC3000';

  public static CONSULTAR_TIPO_PAGO = 'APTIPA0000';
  public static AGREGAR_TIPO_PAGO = 'APTIPA1000';
  public static EDITAR_TIPO_PAGO = 'APTIPA2000';
  public static ELIMINAR_TIPO_PAGO = 'APTIPA3000';

  public static CONSULTAR_REPORTE_PRODUCTIVIDAD = 'APRPPR0000';
  public static CONSULTAR_REPORTE_EJECUTIVO = 'APREJ0000';

  public static CONSULTAR_OPCION_VENTA = 'APOPVE0000';
  public static AGREGAR_OPCION_VENTA = 'APOPVE1000';
  public static EDITAR_OPCION_VENTA = 'APOPVE2000';
  public static ELIMINAR_OPCION_VENTA = 'APOPVE3000';

  public static CONSULTAR_CONFIGURACION_OPCION_VENTA = 'APCOPV0000';
  public static AGREGAR_CONFIGURACION_OPCION_VENTA = 'APCOPV1000';
  public static EDITAR_CONFIGURACION_OPCION_VENTA = 'APCOPV2000';
  public static ELIMINAR_CONFIGURACION_OPCION_VENTA = 'APCOPV3000';

  public static CONSULTAR_MERCADO = 'APMRCD0000';
  public static AGREGAR_MERCADO = 'APMRCD1000';
  public static EDITAR_MERCADO = 'APMRCD2000';
  public static ELIMINAR_MERCADO = 'APMRCD3000';

  public static BITACORA_MOVIMIENTO_USUARIO = 'APBIMU0000';

  // Abrir Caja
  public static ABRIR_CAJA = 'APABCA0000';

  // Corte de Caja
  public static CORTE_CAJA = 'APCOCA0000';

  // Cierre del Dia
  public static CIERRE_DEL_DIA = 'APCIDI0000';
  public static VER_REPORTE_CAJERO_GLOBAL = 'APCIDI0001';
  public static VER_REPORTE_OTROS_PAGOS = 'APCIDI0002';

  // Gestion de Pacientes - Urgencias
  public static CONSULTAR_URGENCIAS = 'APUGNC0000';

  // Listas de precio
  public static CONSULTAR_LISTA_PRECIO = 'APLTPR0000';
  public static AGREGAR_LISTA_PRECIO = 'APLTPR1000';
  public static EDITAR_LISTA_PRECIO = 'APLTPR2000';
  public static ELIMINAR_LISTA_PRECIO = 'APLTPR3000';

  // Gestion de recibos
  public static GESTION_RECIBOS_APLICAR_DEVOLUCION = 'APGERB4000';
  public static GESTION_LIQUIDACIONES = 'APGELQ0000';
  public static GESTION_LIQUIDACIONES_PAGO = 'APGELQ4000';

  //Gestion de gastos
  //Nota Gasto
  public static CONSULTAR_NOTA_GASTO = 'APNTGS0000';
  public static AGREGAR_NOTA_GASTO = 'APNTGS1000';
  public static EDITAR_NOTA_GASTO = 'APNTGS2000';
  public static ELIMINAR_NOTA_GASTO = 'APNTGS3000';
  public static PAGAR_NOTA_GASTO = 'APNTGS5000';

  //Flujo de efectivo
  //Gestor de pagos
  // TODO: Validar si se debe cambiar el nombre del acceso (CONSULTAR_NOTA_FLUJO)
  public static CONSULTAR_GESTOR_PAGO = 'APGSPG0000';
  public static AGREGAR_NOTA_FLUJO = 'APGSPG1000';
  public static APROBAR_NOTA_FLUJO = 'APGSPG4000';
  public static DECLINAR_NOTA_FLUJO = 'APGSPG5000';

  public static NOTA_FLUJO_CAJA = 'APGNCJ0000';

  public static CONSULTAR_SOLICITUD_MOVIMIENTO_SAT = 'APSOMS0000';
  public static AGREGAR_SOLICITUD_MOVIMIENTO_SAT = 'APSOMS1000';
  public static VERIFICAR_SOLICITUD_MOVIMIENTO_SAT = 'APSOMS2000';

  public static CONSULTAR_TIPO_EXPEDIENTE_ADMINISTRATIVO = 'APTIEA0000';
  public static AGREGAR_TIPO_EXPEDIENTE_ADMINISTRATIVO = 'APTIEA1000';
  public static EDITAR_TIPO_EXPEDIENTE_ADMINISTRATIVO = 'APTIEA2000';
  public static ELIMINAR_TIPO_EXPEDIENTE_ADMINISTRATIVO = 'APTIEA3000';


  // Configuración de Entidades

  public static CONFIGURADOR_SECCION = 'APCOSI0000';
  public static AGREGAR_SECCION = 'APCOSI1000';
  public static EDITAR_SECCION = 'APCOSI2000';
  public static ELIMINAR_SECCION = 'APCOSI3000';

  public static CONFIGURADOR_ENTIDAD = 'APENTI0000';
  public static AGREGAR_ENTIDAD = 'APENTI1000';
  public static EDITAR_ENTIDAD = 'APENTI2000';
  public static ELIMINAR_ENTIDAD = 'APENTI3000';

  // Gestión de Pacientes:
  public static CONSULTAR_EXPEDIENTE_PACIENTE = 'APEXPA0000';
  public static AGREGAR_EXPEDIENTE_PACIENTE = 'APEXPA1000';
  public static EDITAR_EXPEDIENTE_PACIENTE = 'APEXPA2000';
  public static ELIMINAR_EXPEDIENTE_PACIENTE = 'APEXPA3000';


  //Acceso a proyectos

  public static SISTEMA_DISTRIBUCION = 'APSDIT0000';
}
